name: tests

on:
    push:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install GNAT Pro
              uses: ./contrib/RecordFlux/.github/actions/install_gnat_pro
              with:
                  version: "23.0w-20220202"
                  ssh_key: ${{ secrets.MEMCACHED_SSH_KEY }}
                  server: ${{ secrets.MEMCACHED_SERVER }}
            - name: Install GNAT Pro (ARM)
              uses: ./contrib/RecordFlux/.github/actions/install_gnat_pro
              with:
                  version: "23.0w-20220202"
                  target: "arm-elf"
                  host_arch: "linux64"
                  ssh_key: ${{ secrets.MEMCACHED_SSH_KEY }}
                  server: ${{ secrets.MEMCACHED_SERVER }}
            - name: Install GNAT Pro (RISC-V 32)
              uses: ./contrib/RecordFlux/.github/actions/install_gnat_pro
              with:
                  version: "23.0w-20220202"
                  target: "riscv32-elf"
                  host_arch: "linux64"
                  ssh_key: ${{ secrets.MEMCACHED_SSH_KEY }}
                  server: ${{ secrets.MEMCACHED_SERVER }}
            - name: Install GNAT Pro (RISC-V 64)
              uses: ./contrib/RecordFlux/.github/actions/install_gnat_pro
              with:
                  version: "23.0w-20220202"
                  target: "riscv64-elf"
                  host_arch: "linux64"
                  ssh_key: ${{ secrets.MEMCACHED_SSH_KEY }}
                  server: ${{ secrets.MEMCACHED_SERVER }}
            - name: Install SPARK Pro
              uses: ./contrib/RecordFlux/.github/actions/install_spark_pro
              with:
                  version: "23.0w-20220128"
                  ssh_key: ${{ secrets.MEMCACHED_SSH_KEY }}
                  server: ${{ secrets.MEMCACHED_SERVER }}
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y expect python python3-dev python3-setuptools
                  echo "/canary (for systems using strange)/paths" >> $GITHUB_PATH
            - name: Test
              run: make
