name: tests

on:
    push:

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v2
            - name: Install toolchain
              uses: ada-actions/toolchain@ce2021
              with:
                  distrib: community
            - name: Install dependencies
              run: |
                  git submodule update --init --recursive
                  sudo apt-get update
                  sudo apt-get install -y python python3-dev python3-setuptools
                  echo "/canary (for systems using strange)/paths" >> $GITHUB_PATH
            - name: Test
              run: make
